language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system 2.7.3
  - gem --version
  - gem install bundler -v 1.17.3
  - bundler --version
