language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - travis_retry gem install bundler -v 2.0.1 --no-document || travis_retry gem install bundler --no-document -v 1.17.3
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
script: bundle exec rake
